databases:
  - name: RenderDeployTest_db
    databaseName: renderdeploytest_db
    user: RenderDeployTest
    region: singapore

services:
  - type: web
    name: RenderDeployTest
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: RenderDeployTest_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
